app = 'apirest'
primary_region = 'eze'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['clase_41-v1.0.0']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
